@startuml

title __SETTINGS's Class Diagram__\n

  namespace Settings {
    class Settings.Settings {
        {static} + HOST_NAME : String
        {static} + RMIPort : int
        {static} + TCPBUFFLEN : int
        {static} + TCPPort : int
        {static} + TIMEOUT : int
        {static} + UDPPort : int
        {static} + X : int
        {static} + Y : int
        {static} + Z : int
        {static} + k : int
        {static} + timer : long
    }
  }
  

  namespace Settings {
    enum AMICIZIA {
      ACCETTATA
      RICHIESTA
      RIFIUTATA
    }
  }
  

  namespace Settings {
    enum GetType {
      AMICI
      CLASSIFICA
      PENDING
    }
  }
  

  namespace Settings {
    enum REQUEST {
      AMICIZIA
      GET
      LOGIN
      LOGOUT
      PAROLA
      SFIDA
    }
  }
  

  namespace Settings {
    enum RESPONSE {
      AMICI
      AMICIZIA
      CLASSIFICA
      LOGIN
      NOK
      OK
      PAROLA
      PENDING
      SFIDA
    }
  }
  

  namespace Settings {
    enum RQTType {
      ACCETTA
      RICHIEDI
      RIFIUTA
    }
  }
  

  namespace Settings {
    enum SFIDA {
      ACCETTATA
      INIZIATA
      RICHIESTA
      RIFIUTATA
      SCADUTA
      TERMINATA
    }
  }
  

  Settings.Settings +-down- Settings.Settings.AMICIZIA
  Settings.Settings +-down- Settings.Settings.GetType
  Settings.Settings +-down- Settings.Settings.REQUEST
  Settings.Settings +-down- Settings.Settings.RESPONSE
  Settings.Settings +-down- Settings.Settings.RQTType
  Settings.Settings +-down- Settings.Settings.SFIDA


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
